locations = ['spain','mexico','canada','chile','disney land','moon','mercury']
print("\nThis is the original list of our possible locations: ")
print(locations)
print("")
print(sorted(locations))
print("")
print(locations)
print("")
print(sorted(locations, reverse=True))
print("")
print(locations)
locations.reverse()
print("")
print(locations)
locations.reverse()
print("")
print(locations)
locations.sort()
print("")
print(locations)
print("")
locations.sort(reverse=True)
print(locations)